server {
    listen 8082;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.geojson$ {
        root /data;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
